repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
    -   id: black
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.11
    hooks:
    -   id: ruff
    -   id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.18.2'
    hooks:
    -   id: mypy
        exclude: ^(docs|tests)/
